### ISSUE TITLE
needs source code

### ISSUE THREAD

**Issue by axsddlr** [Gabryy-yy/Valorant-InstaLocker#1]
source code?

**Comment by gaprj** [comment]
For what?

**Comment by axsddlr** [comment]
dont trust just a random exe on github lol

**Comment by gaprj** [comment]
Oh okay lol, it's a simple python script, in the readme I attached a YouTube video showing how the software works.
Anyway, if you really want the code, i can update the repository tomorrow :)

**Comment by gaprj** [comment]
I'll send you a message as soon as I've added the code.

**Comment by axsddlr** [comment]
good practice if youre uploading to github, source code would be as well. reputable

**Comment by gaprj** [comment]
First time uploading to GitHub

**Comment by gaprj** [comment]
I uploaded the source code
