### ISSUE TITLE
-

### ISSUE THREAD

**Issue by teoobarca** [Gabryy-yy/Valorant-InstaLocker#2]
-

**Comment by gaprj** [comment]
The valorant api can't take your agents before the game starts

**Comment by OwOHamper** [comment]
> The valorant api can't take your agents before the game starts

yes

**Comment by gaprj** [comment]
Nope bro

**Comment by gaprj** [comment]
I checked

**Comment by OwOHamper** [comment]
i have it programmed

**Comment by OwOHamper** [comment]
When there is match found it counts as pregame and on pregame you can already lock agents

**Comment by gaprj** [comment]
I'll take a look... But isn't it bannable that way?

**Comment by OwOHamper** [comment]
> I'll take a look... But isn't it bannable that way?

I dont think and if it would clicking on screen would be too

**Comment by gaprj** [comment]
Yes, it should, but in this way it is not detectable as the autoclicker runs at "human" speed

**Comment by gaprj** [comment]
If the api could instalock even before the match is found, in my opinion it would be banned
